### ISSUE TITLE
Catalogue doesn't have list of all countries for which dataset is available

### ISSUE THREAD

**Issue by harshvardhaniimi** [wpgp/wopr#22]
The catalogue lists only 51 countries for which data is available. The population dataset is available only for eight countries. Can this be updated, please? Could you please help me out if I'm missing something?

I know other datasets are available (for example, here's a [list of datasets for India](https://data.humdata.org/organization/worldpop?q=india&ext_page_size=25)).

```
> catalouge = getCatalogue() %>% as_tibble()

> catalouge %>% filter(category == "Population") %>% distinct(country)
# A tibble: 8 x 1
  country
  <chr>  
1 BFA    
2 COD    
3 GHA    
4 MOZ    
5 NGA    
6 SLE    
7 SSD    
8 ZMB


> catalouge %>% distinct(country)
# A tibble: 51 x 1
   country
   <chr>  
 1 AGO    
 2 BDI    
 3 BEN    
 4 BFA    
 5 BWA    
 6 CAF    
 7 CIV    
 8 CMR    
 9 COD    
10 COG    
# … with 41 more rows
```

**Comment by doug-leasure** [comment]
Hey @harshvardhaniimi ,

Thanks for your question.  

The `wopr` R package only provides access to bespoke population estimates that we have produced for individual countries.  The wopr catalogue should include everything available from [wopr.worldpop.org](https://wopr.worldpop.org).  

The global datasets you are looking for are available from the WorldPop FTP server: ftp://ftp.worldpop.org/GIS/Population/.  You can download files via ftp from the R console using the `utils` package:

``` 
utils::download.file(url = "ftp://ftp.worldpop.org/GIS/Population/Global_2000_2020/2020/IND/ind_ppp_2020.tif",
                     destfile = "ind_ppp_2020.tif",
                     mode="wb",
                     quiet=FALSE,
                     method="libcurl")
```

I hope this helps.

Best,
-Doug
