### ISSUE TITLE
retrieve age-sex proportions from API end-point

### ISSUE THREAD

**Issue by edarin** [wpgp/wopr#24]

**Comment by bondarenkom** [comment]
New endpoint was included to API,  example is 
/v1/wopr/proportionsagesex?iso3=NGA&ver=1.2&id=2 or to get all agesex is /v1/wopr/proportionsagesex?iso3=NGA&ver=1.2&id=null

**Comment by edarin** [comment]
I still have to implement it in woprVision @bondarenkom ! ;)
