### ISSUE TITLE
OperationalError: GIN v1.0

### ISSUE THREAD

**Issue by doug-leasure** [wpgp/wopr#32]
I am getting intermittent errors when clilcking the "Submit" button for GIN v1.0:

```
simpleWarning: No User Description for this type of error: OperationalError
```

The error only occurs for some locations and it sometimes returns the population estimate, but othertimes it doesn't.

**Comment by edarin** [comment]
This issue was also happening for other datasets this morning. It was not happening on the dev server. I've reinstalled at lunch time on the main server and it seems to have solved the issue. I keep it open for now.
